services:
#    ea.dashboard.bundle:
#        class: EasyAdminFriends\EasyAdminDashboardBundle\Controller\DefaultController
#        calls:
#            - [setContainer, ["@service_container"]]
#        public: true